server:
  port: 8090

security:
  oauth2:
    resource:
      token-info-uri: http://keycloak.k8.wildwidewest.xyz/auth/realms/meltingpoc/protocol/openid-connect/token/introspect
    client:
      clientId: meltingpoc
      clientSecret: 4a5bac8a-87e2-4ce1-a417-75f9f70bebef
      accessTokenUri: http://keycloak.k8.wildwidewest.xyz/auth/realms/meltingpoc/protocol/openid-connect/token
      userAuthorizationUri: http://keycloak.k8.wildwidewest.xyz/auth/realms/meltingpoc/protocol/openid-connect/auth